package:
  name: aqtest
  version: "0.1"

build:
  number: 1

source:
  url: https://github.com/LYC-vio/Aqtest/archive/v0.0.1.tar.gz
  sha256: 4f04cb0b76349014cc0dd1b3830b7d29469fdff223788e95c24f1edfac52fffb

requirements:
  build:
    - python
    - setuptools
    - samtools
    - minimap2
    - scipy
    - numpy
    - pysam

  run:
    - python
    - samtools
    - minimap2
    - scipy
    - numpy
    - pysam

about:
  summary: This is a simple test
