package:
  name: aqtest
  version: "0.1"

build:
  noarch: python
  number: 0

source:
  url: https://github.com/LYC-vio/Aqtest/archive/v0.0.2.tar.gz
  sha256: 1a7ae40966dbbfc99d791f951a1f4671c0f36ff4288656a4374d19fc93cdcae9

requirements:
  build:
    - python
    - setuptools >=1.1
    - samtools
    - minimap2 ==2.17
    - scipy
    - numpy
    - pysam


  run:
    - python
    - samtools
    - minimap2 ==2.17
    - scipy
    - numpy
    - pysam

test:
  commands:
    - step1 --help
    - step2 --help
    - assemble --help
    - phasing --help

about:
  home: https://github.com/LYC-vio/Aqtest
  license: MIT
  summary: This is a simple test
